

	<main>

		<section id="blocImageAccueil">

			<div class="flexslider">
			  <ul class="slides">
			    <li>
			      <img src="img/flexslider/1.jpg" />
			    </li>
			    <li>
			      <img src="img/flexslider/2.jpg" />
			    </li>
			    <li>
			      <img src="img/flexslider/3.jpg" />
			    </li>
			    <li>
			      <img src="img/flexslider/4.jpg" />
			    </li>
			    <li>
			      <img src="img/flexslider/5.jpg" />
			    </li>
			    <li>
			      <img src="img/flexslider/6.jpg" />
			    </li>
			  </ul>
			</div>
		
		</section>
	 
		<section id="introduction">
			
			<img src="img/profil.jpg">
			<p class="texteIntro">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Numquam consequatur nostrum fuga dignissimos iusto cumque porro eius odio voluptatum dolorum, obcaecati, temporibus incidunt nobis consectetur aliquid doloremque. Excepturi, eius, perspiciatis! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam rerum ex ratione laudantium cumque, ad esse? Unde voluptates molestias sed modi inventore magnam autem sequi repellat, obcaecati est odio perspiciatis.</p>

		</section>

		
		</main>

	<script>
		$(window).on('load',function() {
		  $('.flexslider').flexslider({
		    animation: "fade"
		  });
		});
	</script>