		
	<main>

		<section id="mosaique" class="container">
			
			<div class="imageMosaique"><a href="?p=leProjet"><img src="img/mosaique/1.jpg"><div class="texteVignette">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit, cupiditate ipsam consequuntur esse ipsum soluta assumenda debitis laborum incidunt reiciendis animi, at eaque, fuga amet. Nesciunt impedit alias laborum recusandae.</div></a></div>
			<div class="imageMosaique"><a href=""><img src="img/mosaique/2.jpg"><div class="texteVignette">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero saepe eius magnam iusto. Esse reiciendis sapiente quis consectetur, nostrum voluptas illum, ad tempora corporis deleniti voluptatum voluptates provident culpa nesciunt?</div></a></div>
			<div class="imageMosaique"><a href=""><img src="img/mosaique/3.jpg"><div class="texteVignette">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero saepe eius magnam iusto. Esse reiciendis sapiente quis consectetur, nostrum voluptas illum, ad tempora corporis deleniti voluptatum voluptates provident culpa nesciunt?</div></a></div>
			<div class="imageMosaique"><a href=""><img src="img/mosaique/4.jpg"><div class="texteVignette">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero saepe eius magnam iusto. Esse reiciendis sapiente quis consectetur, nostrum voluptas illum, ad tempora corporis deleniti voluptatum voluptates provident culpa nesciunt?</div></a></div>
			<div class="imageMosaique"><a href=""><img src="img/mosaique/5.jpg"><div class="texteVignette">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero saepe eius magnam iusto. Esse reiciendis sapiente quis consectetur, nostrum voluptas illum, ad tempora corporis deleniti voluptatum voluptates provident culpa nesciunt?</div></a></div>
			<div class="imageMosaique"><a href=""><img src="img/mosaique/6.jpg"><div class="texteVignette">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero saepe eius magnam iusto. Esse reiciendis sapiente quis consectetur, nostrum voluptas illum, ad tempora corporis deleniti voluptatum voluptates provident culpa nesciunt?</div></a></div>
			<div class="imageMosaique"><a href=""><img src="img/mosaique/7.jpg"><div class="texteVignette">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero saepe eius magnam iusto. Esse reiciendis sapiente quis consectetur, nostrum voluptas illum, ad tempora corporis deleniti voluptatum voluptates provident culpa nesciunt?</div></a></div>
			<div class="imageMosaique"><a href=""><img src="img/mosaique/8.jpg"><div class="texteVignette">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero saepe eius magnam iusto. Esse reiciendis sapiente quis consectetur, nostrum voluptas illum, ad tempora corporis deleniti voluptatum voluptates provident culpa nesciunt?</div></a></div>

		</section>

	</main>