<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="css/normalize.css">
	<link rel="stylesheet" type="text/css" href="css/admin.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<title>Administration</title>
</head>
<body>


<main id="blocAdmin">

	<h1>Administration</h1>

	<div class="blocLiensAdmin">

		<a href="/SiteEmilie/">Page d'accueil</a>
		<a href="#nouveauProjet">Nouveau projet</a>	
		<a href="#introEdit">Modifier le texte d'intro</a>
		<a href="#imagesSlider">Modifier les images du slider</a>
		<a href="change">Changer le mot de passe</a>
		<a href="signout">Se déconnecter</a>

	</div>

	<section class="messages">
		
		<?php 
		
			if (isset($_SESSION['intro']) && $_SESSION['intro'] == 'ok') { 

				$_SESSION['intro'] = '';
		
		?>
				<h2 id="successMessage"> <i class="fas fa-check"></i> L'introduction a bien été modifiée </h2>

		<?php 
		
			}

			if (isset($_SESSION['error']) && $_SESSION['error'] == 'projet') { ?>

				<h2 id="errorMessage"> <i class="fas fa-times"></i> Une erreur s'est produite </h2>

			<?php } ?>


	</section>

<!-- LISTE PROJETS --> 


	<section id="listeProjets">

	<h2>- Projets -</h2>

	<?php foreach ($projets as $theProjet) : ?>
		
		<article>
			<div>
				<h2><?= $theProjet['titre'] ?>
				<?php 
				if ($theProjet['published']) {
					?>

					<span class='italic'>(Publié)</span>

					
				<?php } else { ?>
					
					<span class='italic'>(Non publié)</span>

				<?php } ?>

				</h2>

			</div>
			<div><h3><span class="italic">Texte galerie : <br></span><?= $theProjet['texteGalerie'] ?></h3></div>
			<div><h3><span class="italic">Sous-titre : </span><br><?= $theProjet['sousTitre'] ?></h3></div>
			<div><h3><span class="italic">Texte (extrait) : </span><br><?= substr( $theProjet['texte'],0,100) ?> ... </h3></div>
			<div class="displayTitleImage">
				<h3>Image Galerie :</h3>

<?php if (!empty($theProjet['imageTitre'])) { ?>

	<img src="img/imagesArticles/<?=$theProjet['imageTitre']?>" alt="<?=$theProjet['imageTitre']?>">


<?php } else { ?>

	<p class="noPicture">Pas d'image chargée</p>

<?php } ?>

 
			</div>
			
			<div class="galleryMiniatures"><h3>Images de l'article :</h3>
				<?php if (!empty($theProjet['imagesArticle'])) {

				$listeImages = explode(",",$theProjet['imagesArticle']);
				foreach ($listeImages as $image) {
					echo '<img class="imgMiniature" src="img/imagesArticles/' . $image . '" alt="'.$image.'">';
				}

			} else { ?>

				<p class="noPicture">Pas d'image</p>

			<?php } ?>

			</div>
			<div class="articleTools">
				<a href= <?= $theProjet['id'] ?>>Modifier 
					<i class="fas fa-marker"></i>
				</a>

			</div>

		</article>
		
	<?php endforeach ?>

<!-- NOUVEAU PROJET --> 

	</section>

	<section id="nouveauProjet">

		<h2>- Nouveau projet -</h2>

		<form action="controller/projectNewController.php" method="POST">

			<label for="title">Titre du projet :</label>
			<input type="text" placeholder="Titre" id="title" name="title">

			<label for="galleryText">Texte de présentation (galerie) :</label>
			<textarea name="galleryText" id="galleryText" cols="30" rows="5"> ... </textarea>

			<label for="subtitle">Sous-titre :</label>
			<textarea name="subtitle" id="subtitle" cols="30" rows="5"></textarea>

			<label for="text">Texte :</label>
			<textarea name="text" id="text" cols="30" rows="10"></textarea>
			
			<label class="publishLabel" for="published">Cocher pour publier</label>
			<input id="publicationCheckbox" name="published" type="checkbox" value="1">

			<input id="submitNewProject" type="submit" value="Enregistrer et ajouter des images">




		</form>

	</section>

	<hr>

	<!-- TEXTE INTRO --> 

	<section id="introEdit">

		<h2>- Modifier le texte de présentation -</h2>

		<form class="introForm" action="model/introEdit.php" method="post">

			<label for="newIntro">Texte actuel :</label>
			<textarea name="newIntro" id="intro" cols="30" rows="10"><?= $intro['texte'] ?></textarea>
			<input type="submit" value="Modifier">
		</form>

	</section>

	<!-- IMAGES SLIDER -->

	<section id="imagesSlider">

	<h2>- Modifier les images du slider -</h2>

	<form class="imagesForm" action="model/imagesslider.php?images=slider" method="POST" enctype="multipart/form-data">
	
	<label for="imagesSlider">Ajouter des images au slider :</label>
	<input type="file" name="imagesSlider[]" multiple>

	<input  id="imagesSliderSubmit" type="submit" value="Ajouter">

	<div class="displayImagesForm">

	<?php 
       
       if (isset($imagesSlider) && isset($imagesSlider[0]) && $imagesSlider[0] != "") {

                foreach ($imagesSlider as $image) { 

                    if ($image != "") { ?>
                    <img class="imgMiniature" src="img/flexslider/<?=$image?>" alt="Image Slider">
                    <a class="deleteButton" href="model/imagesslider.php?images=slider&dsid=<?=$image?>"><i class="fas fa-trash-alt"></i></a>
                    <?php } ?>
                <?php } 
                
            } else { ?>

                <h3 class="noPicture">Pas d'image</h3>

              <?php  } var_dump($imagesSlider);
                
                ?>
        
        </div>

	</form>
	
	</section>

</main>

	
</body>

<script>

if (document.getElementById('successMessage') != null) {
	$message = document.getElementById('successMessage');
	$message.style.transition = "all 0.5s ease";
	setTimeout(function () {
		$message.style.opacity = "0";
	} , 3000)
	setTimeout(function () {
		$message = document.getElementById('successMessage');
		$message.style.transform = "scale(0)";
		$message.style.margin = "0";
	} , 3500)
        }

</script>

</html>