<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="css/normalize.css">
	<link rel="stylesheet" type="text/css" href="css/admin.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<title>Document</title>
</head>
<body>


<main id="blocAdmin">

	<h1>Administration</h1>

	<div class="blocLiensAdmin">

		<a href="/SiteEmilie/">Page d'accueil</a>
		<a href="controller/changePasswordController.php">Changer le mot de passe</a>
		<a href="signout.php">Se déconnecter</a>


	</div>

	<section id="listeProjets">

	<h2>Projets</h2>

	<table class="tableauProjets">

	<thead>
		<tr>
			<th>Titre</th>
			<th>Sous-titre</th>
			<th>Texte</th>
			<th>Images</th>
			<th>Modifier</th>
		</tr>
	</thead>
	<?php foreach ($projets as $theProjet) : ?>
		
		<tr>
			<th><?= $theProjet['titre'] ?></th>
			<th><?= $theProjet['sousTitre'] ?></th>
			<th><?= substr( $theProjet['texte'],0,100) ?> ... </th>
			<th>
				<?php
				$listeImages = explode(",",$theProjet['imagesArticle']);
				foreach ($listeImages as $image) {
					echo '<img class="imgMiniature" src="img/imagesArticles/' . $image . '.jpg" alt="Image Article">';
				}
				?>
			</th>
			<th><a href= <?= $theProjet['id'] ?>><i class="fas fa-marker"></i></a></th>
		</tr>
		
	<?php endforeach ?>

	</table>


	</section>

</main>

	
</body>
</html>