<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="css/normalize.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
	<script
			  src="https://code.jquery.com/jquery-3.4.1.min.js"
			  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
			  crossorigin="anonymous"></script>
	<!-- include libraries(jQuery, bootstrap) -->
	<link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">
	<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script> 
	<script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"></script> 

	<!-- include summernote css/js -->
	<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css" rel="stylesheet">
	<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.js"></script>

	<link rel="stylesheet" type="text/css" href="css/admin.css">
	<script type='text/javascript' src='js/admin.js'></script>
			  
	<title>Administration</title>
</head>
<body>

<main id="blocAdmin">

	<h1>Administration</h1>

	<div class="blocLiensAdmin">

		<a href="index">Page d'accueil</a>
		<a href="#nouveauProjet">Nouveau projet</a>	
		<a href="#introImageEdit">Modifier l'image d'intro</a>
		<a href="#introEdit">Modifier le texte d'intro</a>
		<a href="#imagesSlider">Modifier les images du slider</a>
		<a href="change">Changer le mot de passe</a>
		<a href="signout">Se déconnecter</a>

	</div>

	<div id="backToTheTop">
		<a href="#blocAdmin"><i class="fas fa-caret-up"></i></a>
	</div>

	<?php if (isset($_SESSION['messages']) && !empty($_SESSION['messages'])) { ?>

	<section class="messages">
		
		<?php foreach ($_SESSION['messages'] as $message) {
			echo $message;
			$_SESSION['messages'] = [];
		 } ?>

	</section>

<?php } ?>

<!-- LISTE PROJETS --> 

	<section id="listeProjets">

	<h2>- Projets -</h2>

	<?php if (empty($projets)) {

		echo '<h3 class="italic">Pas de projets</h3>';

	} else {

	 foreach ($projets as $theProjet) : ?>
		
		<article>
			<div>
			<?php 
				if ($theProjet['published']) {
					?>

					<span class='published'>Publié</span>

					
				<?php } else { ?>
					
					<span class='unpublished'>Non publié</span>

				<?php } ?>
				<h2><?= $theProjet['titre'] ?></h2>
				
			</div>
			<div>
				<h3 class="">Texte galerie</h3>
				<p><?= $theProjet['texteGalerie'] ?></p>
			</div>
			<div>
				<h3 class="">Sous-titre</h3>
				<p><?= $theProjet['sousTitre'] ?></p>
			</div>
			<div>
				<h3 class="">Texte (extrait)</h3>
				<p><?= substr( $theProjet['texte'],0,100) ?> ... </p>
			</div>
			<div class="displayTitleImage">
				<h3>Image Galerie</h3>

<?php if (!empty($theProjet['imageTitre'])) { ?>

	<img src="img/imagesArticles/<?=$theProjet['imageTitre']?>" alt="<?=$theProjet['imageTitre']?>">


<?php } else { ?>

	<p class="noPicture">Pas d'image chargée</p>

<?php } ?>

 
			</div>
			
			<div class="galleryMiniatures"><h3>Images de l'article</h3>
				<?php if (!empty($theProjet['imagesArticle'])) {

				$listeImages = explode(",",$theProjet['imagesArticle']);
				foreach ($listeImages as $image) { 
					if ($image != "" && $image != " ") {
					echo '<img class="imgMiniature" src="img/imagesArticles/' . $image . '" alt="'.$image.'">';
				}
			}

			} else { ?>

				<p class="noPicture">Pas d'image</p>

			<?php } ?>

			</div>
								<!-- WIP WIP WIP -->
			<div class="galleryMiniatures"><h3>Images plans</h3>
				<?php if (!empty($theProjet['imagesTextArticle'])) {

				$listeImagesText = explode(",",$theProjet['imagesTextArticle']);
				foreach ($listeImagesText as $image) { 
					if ($image != "" && $image != " ") {
					echo '<img class="imgMiniature" src="img/imagesArticles/' . $image . '" alt="'.$image.'">';
				}
			}

			} else { ?>

				<p class="noPicture">Pas d'image</p>

			<?php } ?>

			</div>


			<div class="articleTools">
				<a href="index?p=theProject&n=<?= $theProjet['id'] ?>">Voir 
					<i class="fas fa-eye"></i>
				</a>
				<a href="projectEdit?pid=<?= $theProjet['id'] ?>">Modifier 
					<i class="fas fa-marker"></i>
				</a>
				<?php if ($theProjet['published'] == TRUE) { ?>
				<a href="model/togglePublished.php?pid=<?=$theProjet['id']?>">Dépublier 
				<i class="fas fa-toggle-on"></i>
				</a>
				<?php } else if ($theProjet['published'] == FALSE) { ?>
					<a href="model/togglePublished.php?pid=<?=$theProjet['id']?>">Publier 
				<i class="fas fa-toggle-off"></i>
				</a>
				<?php } ?>
				<a id="buttonDeleteProject" class="buttonDeleteProject" href="model/deletion.php?pdid=<?= $theProjet['id']?>">Supprimer 
					<i class="fas fa-times"></i>	
				</a>

			</div>

		</article>
		
				<?php endforeach;
	
					}	?>





<!-- NOUVEAU PROJET --> 

	</section>

	<hr>


	<section id="nouveauProjet">

		<h2>- Nouveau projet -</h2>

		<form action="controller/projectNewController.php" method="POST">

			<label for="title">Titre du projet :</label>
			<input type="text" placeholder="" id="title" name="title">

			<label for="galleryText">Texte de présentation (galerie) :</label>
			<textarea name="galleryText" id="galleryText" cols="30" rows="5"></textarea>

			<label for="subtitle">Sous-titre :</label>
			<textarea name="subtitle" id="subtitle" cols="30" rows="5"></textarea>

			<label for="text">Texte :</label>
			<textarea name="text" id="text" cols="30" rows="10"></textarea>
			
			<label class="publishLabel" for="published">Cocher pour publier</label>
			<input id="publicationCheckbox" name="published" type="checkbox" value="1">

			<input id="submitNewProject" type="submit" value="Enregistrer et ajouter des images">

		</form>

	</section>

	<hr>

	<!-- IMAGE INTRO --> 

	<section id="introImageEdit">

		<h2 class="alignCenter">- Modifier l'image de présentation -</h2>

		<form class="imagesForm" action="model/introImageEdit.php" method="POST" enctype="multipart/form-data">

			<label for="imageIntro">Changer l'image d'intro (format carré - 2 Mo maximum):</label>
			<input type="file" name="imageIntro">

			<input id="imageIntroSubmit" type="submit" value="Modifier">

			<div class="displayIntroImage">

				<label for="">Image actuelle : </label>

				<?php if (isset($imageIntro) && !empty($imageIntro)) { ?>

					<img src="img/imageIntro/<?=$imageIntro['name']?>" alt="Image Intro">

				<?php } else { ?>

					<h3 class="noPicture">Pas d'image</h3>

				<?php } ?>

			</div>

		</form>

	</section>

	<hr>

	<!-- TEXTE INTRO --> 

	<section id="introEdit">

		<h2 class="alignCenter">- Modifier le texte de présentation -</h2>

		<form class="introForm" action="model/introEdit.php" method="post">

			<label for="newIntro">Texte actuel :</label>
			<textarea name="newIntro" id="newIntro" cols="30" rows="10"><?= $intro['texte'] ?></textarea>
			<input type="submit" value="Modifier">
		</form>

	</section>

	<hr>

	<!-- IMAGES SLIDER -->

	<section id="imagesSlider">

	<h2>- Modifier les images du slider -</h2>

	<section class="messages">

		<?php 
		if (isset($_SESSION['slider']) && $_SESSION['slider'] == 'ok') { 
				$_SESSION['slider'] = '';
		?>
				<h2 id="successMessage"> <i class="fas fa-check"></i> Le slider a bien été modifié </h2>
		<?php 
			}

			if (isset($_SESSION['slider']) && $_SESSION['slider'] == 'delete') { 
				$_SESSION['slider'] = '';
		?>
				<h2 id="successMessage"> <i class="fas fa-check"></i> L'image a bien été supprimée </h2>
		<?php 
			}
		?>

	</section>

	<form class="imagesForm" action="model/imagesslider.php?images=slider" method="POST" enctype="multipart/form-data">
	
	<label for="imagesSlider">Ajouter des images au slider (2 Mo maximum) :</label>
	<input type="file" name="imagesSlider[]" multiple>

	<input  id="imagesSliderSubmit" type="submit" value="Ajouter">

	<div class="displayImagesForm">

	<?php 
       
       if (isset($imagesSlider) && isset($imagesSlider[0]) && $imagesSlider[0] != "") {

                foreach ($imagesSlider as $image) { 

										if ($image != "") { ?>
                    <img class="imgMiniature" src="img/flexslider/<?=$image?>" alt="Image Slider">
                    <a class="deleteButton" href="model/imagesslider.php?images=slider&dsid=<?=$image?>"><i class="fas fa-trash-alt"></i></a>
                    <?php } ?>
                <?php } 
                
            } else { ?>

                <h3 class="noPicture">Pas d'image</h3>

              <?php  } ?>
        
        </div>

	</form>
	
	</section>

</main>

<footer class="footerAdmin"></footer>
	
</body>

</html>