<head>

<link rel="stylesheet" href="css/admin.css">
</head>

<main class="passwordChange">

    <h2>- Changer de mot de passe -</h2>
    <form class="customForm" id="passwordChange" action="../model/passwordChange.php" method="post" autocomplete="off" >
        <label for="password">Mot de passe actuel</label>
        <input autocomplete="off" required type="password" name="password" id="password" placeholder="">
        <label for="newPassword">Nouveau mot de passe</label>
        <input autocomplete="off" required type="password" name="newPassword" id="newPassword">
        <label for="newPasswordConfirm">Confirmez le nouveau mot de passe</label>
        <input autocomplete="off" required type="password" name="newPasswordConfirm" id="newPasswordConfirm">
        <input id="submitChangePassword" type="submit" value="Changer">
    </form>

</main>