<main class="passwordChange">

    <h2>Changer de mot de passe</h2>
    <form id="passwordChange" action="../model/passwordChange.php" method="post">
        <label for="password">Mot de passe actuel</label>
        <input required type="password" name="password" id="password">
        <label for="newPassword">Nouveau mot de passe</label>
        <input required type="password" name="newPassword" id="newPassword">
        <label for="newPasswordConfirm">Confirmez le nouveau mot de passe</label>
        <input required type="password" name="newPasswordConfirm" id="newPasswordConfirm">
        <input type="submit" value="Changer">
    </form>

</main>