

<form class="contactForm" action="../contact.php" method="post" onsubmit="return checkForm()">

			<fieldset>

				<legend>Informations personnelles</legend>

				<ul>
					<li>
						<label for="prenom">Prénom : </label>
						<input type="text" name="prenom" id="prenom" onblur="checkPrenom(this)">
						<span class="champErreur" id="erreurPrenom"></span>
					</li>
					<li>
						<label for="nom">Nom : </label>
						<input type="text" name="nom" id="nom" onblur="checkNom(this)">
						<span class="champErreur" id="erreurNom"></span>
					
					</li>

					<li>

						<label for="adresse">Adresse : </label>
						<input type="text" name="adresse" id="adresse" onblur="checkAddress(this)">
						<span class="champErreur" id="erreurAdresse"></span>


					</li>

					<li>
						<label for="codePostal">Code postal : </label>
						<input type="text" name="codePostal" id="codePostal" onblur="checkPostalCode(this)">
						<span class="champErreur" id="erreurCodePostal"></span>

					</li>

					<li>

						<label for="ville">Ville : </label>
						<input type="text" name="ville" id="ville">
						<span class="champErreur" id="erreurVille"></span>


					</li>


					<li>

						<label for="phone">Téléphone (sans espaces) : </label>
						<input type="text" name="phone" id="phone">
						<span class="champErreur" id="erreurVille"></span>


					</li>


				</ul>



			</fieldset>

			<fieldset>

				<legend>Votre message :</legend>

					<ul>
						<li>
							<label for="objet">Objet : </label>
							<input type="text" name="objet" id="objet">
						</li>
						<li>
							<label for="objet">Message : </label>
							<textarea name="objet" id="objet" cols="40" rows="10"></textarea>
						</li>
						<li>
							<input class="buttons" type="button" value="Envoyer" onclick="checkForm()">
						</li>

					</ul>



			</fieldset>


		</form>

		<script type="text/javascript" src="../js/form.js"></script>