<?php 


if (!empty($_POST)) {

	$infos = [];

	foreach ($_POST as $row) {
			if ($row == "" || $row == " ") {
					$row = "Non renseigné";
			}
			// If attempting to send file, GTFO.
			if (strpos($row, "#") === FALSE) {
					$infos[] = clean($row);
			}
	}

	$headers = "MIME-Version: 1.0\r\n";
	$headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";
	
	$mail = 
	"<html><body>" .
	"<h3>Message de " . $infos[0] . "</h3>"
	. "<h3>Email : </h3><p>" . $infos[1] . " </p>"
	. "<h3>Message : </h3><p>" . $infos[2] . "</p>"
	."</body></html>";
	$_SESSION['messages'][] = '<h2 class="message" style="text-align:center;color:green">Votre message a bien été envoyé </h2>';
	mail('jean.annaix@gmail.com','Nouveau message Contact',$mail,$headers);

}


?>

	<section class="missions-header">
		<div class="image-slogan align-center overflow-hidden width-100 height-500 spinner">
				<img class="width-100 loading-image" src="<?= '../img/imageContact/' . getImageContact()['name'] ?>" alt="">
		</div>
		<p class="slogan block width-max-content max-width-80 align-center margin-auto padding-1 background-grey">
				<?= getContactText()['text'] ?>
		</p>
	</section>

<form class="contactForm" action="" method="post">

	<?php if (isset($_SESSION['messages']) && !empty($_SESSION['messages'])) { ?>

	<section class="messages">
		<?php foreach ($_SESSION['messages'] as $message) {
			echo $message;
		} 		
		$_SESSION['messages'] = [];
		?>

	</section>

	<?php } ?>


	<fieldset>

		<ul>
			<li>
				<label for="nom">Nom : *</label>
				<input type="text" name="nom" id="nom" maxlength="40" required>
			
			</li>
			<li>
				<label for="email">Email : *</label>
				<input type="email" name="email" id="email" maxlength="64" required>
			
			</li>
		</ul>
	</fieldset>

	<fieldset>
			<ul>
				<li>
					<label for="message">Message : *</label>
					<textarea name="message" id="message" cols="40" rows="10" required></textarea>
				</li>
				<small style="display:block;text-align:center;padding:5px">*Champs obligatoires</small>
				<li>
					<input class="buttons" type="submit" value="Envoyer">
				</li>
			</ul>
	</fieldset>

</form>

<script src="<?=$to_root?>js/images.js"></script>
