		<footer>
			
			<section id="sectionFooter">
				<img id="logoFooter" src="<?=$to_root?>img/ER_jaunePourFooter.png">
				<article id="infosFooter">
					
					<div>
						<p>/// 88 rue Anatole France, </p>
						<p>38100 <span class="bold" >Grenoble</span> ///</p>
					</div>

					<div>
						<p>Zone d'intervention :</p>
						<p>Grenoble et sa région, Grésivaudan, Chambéry</p>
					</div>

					<div>
						<p>/// 44 A rue du Haut Rochassin,</p>
						<p>38660 <span class="bold">Saint-Vincent-de-Mercuze</span> ///</p>
					</div>

					<div>
						<p>Ouvert du lundi au vendredi de 9h à 18h</p>
						<p>Membre de la coopérative d'activité <a class="bold" href="https://www.cabestan.fr/"> Cabestan</a></p>
					</div>

					
				</article>
			</section>
			
			<nav id="navFooter">
				
				<div>
					<a href="https://www.facebook.com/emilierobert.architecte"><i class="fab fa-facebook-square"></i></a>
					<a href="https://www.instagram.com/emilierobertarchitecte/"><i class="fab fa-instagram"></i></a>
					<a href="https://www.houzz.fr/pro/contact5636/emilie-robert"><i class="fab fa-houzz"></i></a>
				</div>
				<div>
					<a href="https://projets.cotemaison.fr/profil-pro/55442"> Côté maison projets</a>
				</div>
				<div>
					<a href="/index/mentions-legales">Mentions légales</a>
				</div>
			</nav>

			<nav id="navFooter2">
				
			</nav>

		<!-- 

				<div id="copyright">

					<p id="signature">Site réalisé par Jean Annaix</p>
					
				</div>

		-->

		</footer>


  	<script src="<?=$to_root?>js/index.js"></script>

	  
	<script>
		$(window).on('load',function() {
		  $('.flexslider').flexslider({
		    animation: "fade",
		    slideshowSpeed: 3000,
		  });
		});
	</script>


</body>
</html>