<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="css/normalize.css">
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
	<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
	<link rel="stylesheet" href="flexslider/flexslider.css" type="text/css">
	<script src="flexslider/jquery.flexslider.js"></script>

	<title>Émilie Robert - Architecte d'intérieur</title>
</head>

<body>

	<header>
		
		<div id="blocCentreHeader" class="container">

			<div id="blocLogoTitre">
				<img id="ImageTitre" src="img/TitreEMILIESmall.jpg" alt="Émilie Robert">
				<a href="index"><p id="sousTitre"> architecte d'intérieur</p></a>

			</div>

		<a id="parentLogo" href="index">
			<img id="logo" src="img/logoE.png" alt="Émilie Robert">
		</a>

			<nav id="navDesktop">
				
					<a href="?p=projects">projets</a>
					<a href="?p=missions">missions</a>
					<a href="?p=inspirations">inspirations</a>
					<a href="?p=contact">contact</a>

			</nav>

		</div>

			<nav id="navMobile">			
				<i id="logoMenu" class="fas fa-bars"></i>
			</nav>

	</header>
