

	<main>

		<section id="blocImageAccueil">

			<div class="flexslider">
					<ul class="slides">

<?php 

foreach ($imagesSlider as $image) { ?>

						<li>
							<img src="img/flexslider/<?=$image?>" alt="Emilie Robert" />
						</li>

<?php } ?>

			  </ul>
			</div>
		
		</section>
	 
		<section id="introduction">
			
			<img src="img/imageIntro/<?=$imageIntro?>">
			<div class="texteIntro"><?= $intro['texte'] ?></div>

		</section>
		
		</main>


