

	<main>

		<section id="blocImageAccueil">

			<div class="flexslider">
			  <ul class="slides">
			    <li>
			      <img src="img/flexslider/1.jpg" />
			    </li>
			    <li>
			      <img src="img/flexslider/2.jpg" />
			    </li>
			    <li>
			      <img src="img/flexslider/3.jpg" />
			    </li>
			    <li>
			      <img src="img/flexslider/4.jpg" />
			    </li>
			    <li>
			      <img src="img/flexslider/5.jpg" />
			    </li>
			    <li>
			      <img src="img/flexslider/6.jpg" />
			    </li>
			  </ul>
			</div>
		
		</section>
	 
		<section id="introduction">
			
			<img src="img/portraitEmilie.jpg">
			<p class="texteIntro"><?= $intro['texte'] ?></p>

		</section>
		
		</main>

	<script>
		$(window).on('load',function() {
		  $('.flexslider').flexslider({
		    animation: "fade",
		    slideshowSpeed: 3000,
		  });
		});
	</script>

