<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="../css/normalize.css">
	<link rel="stylesheet" type="text/css" href="../css/admin.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <title>Gestion des images</title>
</head>
<body>

<section id="nouveauProjet" >

    <form class="imagesForm" action="../model/images.php" method="POST" enctype="multipart/form-data">

        <label for="imageGallery">Ajouter une image pour la galerie (format 16/9 - 2 Mo maximum) :</label>
        <input type="file" name="imageGallery">

        <input id="imageGallerySubmit" type="submit" value="Ajouter">

        <div class="displayTitleImage">

        <?php if (isset($imgTitle) && !empty($imgTitle)) { ?>

            <img src="../img/imagesArticles/<?=$imgTitle?>" alt="Image Titre">

        <?php } else { ?>

            <h3 class="noPicture">Pas d'image</h3>

        <?php } ?>

        </div>

    </form>

<form class="imagesForm" action="../model/images.php" method="POST" enctype="multipart/form-data">

        <label for="images">Ajouter des images au projet (2 Mo maximum):</label>
        <input type="file" name="images[]" multiple>

        <input  id="imagesProjectSubmit" type="submit" value="Ajouter">

        <div class="displayImagesForm">

       <?php 
       
       if (isset($listeImages) && $listeImages[0] != "") {

                foreach ($listeImages as $image) { 

                    if ($image != "") { ?>
                    <img class="imgMiniature" src="../img/imagesArticles/<?=$image?>" alt="Image Article">
                    <a class="deleteButton newProject" href="images.php?did=<?=$image?>"><i class="fas fa-trash-alt"></i></a>
                    <?php } ?>
                <?php } 
                
            } else { ?>

                <h3 class="noPicture">Pas d'image</h3>

              <?php  } 
                
                ?>
        
        </div>

    </form>

    <a class="link" href="../admin.php">Retour à la gestion des projets</a>
    <a class="link" href="/SiteEmilie?p=theProject&n=<?=$currentProject['id']?> ">Voir la page projet</a>

</section>

</body>
</html>