<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="../css/normalize.css">
	<link rel="stylesheet" type="text/css" href="../css/admin.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>

<section id="nouveauProjet" >

    
    <form class="imagesForm" action="../model/images.php" method="POST" enctype="multipart/form-data">

        <label for="imageGallery">Ajouter une image pour la galerie :</label>
        <input type="file" name="imageGallery">

        <input id="imageGallerySubmit" type="submit" value="Ajouter">


        <div class="displayTitleImage">

            <img src="../img/imagesArticles/<?=$imgTitle?>" alt="Image Titre">

        </div>

        <label for="images">Ajouter des images au projet :</label>
        <input type="file" name="images[]" multiple>

        <input  id="imagesProjectSubmit" type="submit" value="Ajouter">


        <div class="displayImagesForm">

       <?php 
       
				foreach ($listeImages as $image) {
					echo '<img class="imgMiniature" src="img/imagesArticles/' . $image . '.jpg" alt="Image Article">';
                }
                
                ?>

        <?php 

        /***
         * CODE ATELIER PHP
         */
        if (isset($imgList)) {

            foreach ($imgList as $img) { ?>
                <div class="imgList">
                    <img src="img/imagesArticles<?= $img ?>" alt="img">
                    <a class="deleteButton" href="delete.php?id=<?=$img?>"><i class="fas fa-trash-alt"></i></a>
                </div>
                
        <?php } }?>
        

        

        </div>

    </form>

</section>

</body>
</html>