
<div class="container gallery-container">
        
    <div class="tz-gallery">

        <div class="fluid-gallery">

                <div class="double">
                    <a class="lightbox" href="visuels/archi-1.jpg">
                        <img src="visuels/archi-1.jpg" alt="">
                    </a>
                    <a class="lightbox" href="visuels/archi-1.jpg">
                        <img src="visuels/archi-1.jpg" alt="">
                    </a>
                </div>
                <div class="single">
                    <a class="lightbox" href="visuels/archi-6.jpg">
                        <img src="visuels/archi-6.jpg" alt="">
                    </a>
                </div>
                <div class="double">
                    <a class="lightbox" href="visuels/archi-1.jpg">
                        <img src="visuels/archi-1.jpg" alt="">
                    </a>
                    <a class="lightbox" href="visuels/archi-1.jpg">
                        <img src="visuels/archi-1.jpg" alt="">
                    </a>
                </div>
                <div class="single">
                    <a class="lightbox" href="visuels/archi-6.jpg">
                        <img src="visuels/archi-6.jpg" alt="">
                    </a>
                </div>
                <div class="single">
                    <a class="lightbox" href="visuels/archi-6.jpg">
                        <img src="visuels/archi-6.jpg" alt="">
                    </a>
                </div>
                <div class="double">
                    <a class="lightbox" href="visuels/archi-1.jpg">
                        <img src="visuels/archi-1.jpg" alt="">
                    </a>
                    <a class="lightbox" href="visuels/archi-1.jpg">
                        <img src="visuels/archi-1.jpg" alt="">
                    </a>
                </div>
                <div class="single">
                    <a class="lightbox" href="visuels/archi-6.jpg">
                        <img src="visuels/archi-6.jpg" alt="">
                    </a>
                </div>
                <div class="double">
                    <a class="lightbox" href="visuels/archi-1.jpg">
                        <img src="visuels/archi-1.jpg" alt="">
                    </a>
                    <a class="lightbox" href="visuels/archi-1.jpg">
                        <img src="visuels/archi-1.jpg" alt="">
                    </a>
                </div>
                <div class="double">
                    <a class="lightbox" href="visuels/archi-1.jpg">
                        <img src="visuels/archi-1.jpg" alt="">
                    </a>
                    <a class="lightbox" href="visuels/archi-1.jpg">
                        <img src="visuels/archi-1.jpg" alt="">
                    </a>
                </div>
                <div class="single">
                    <a class="lightbox" href="visuels/archi-6.jpg">
                        <img src="visuels/archi-6.jpg" alt="">
                    </a>
                </div>
                <div class="double">
                    <a class="lightbox" href="visuels/archi-1.jpg">
                        <img src="visuels/archi-1.jpg" alt="">
                    </a>
                    <a class="lightbox" href="visuels/archi-1.jpg">
                        <img src="visuels/archi-1.jpg" alt="">
                    </a>
                </div>
                <div class="single">
                    <a class="lightbox" href="visuels/archi-6.jpg">
                        <img src="visuels/archi-6.jpg" alt="">
                    </a>
                </div>

        </div>

    </div>

</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
<script>
    baguetteBox.run('.tz-gallery');
</script>
