
<div class="galerie-inspirations container gallery-container">
    <div class="tz-gallery">
        <div class="fluid-gallery">
            <div class="double">
                <?php if (isset($images_inspirations[0]) && $images_inspirations[0] != "") { ?>
                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[0]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[0]?>" alt="<?= $images_inspirations[0]?>">
                </a>
                <?php } ?>

                <?php if (isset($images_inspirations[1])) { ?>
                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[1]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[1]?>" alt="<?= $images_inspirations[1]?>">
                </a>
                <?php } ?>


            </div>
            <div class="single">
                <?php if (isset($images_inspirations[2])) { ?>
                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[2]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[2]?>" alt="">
                </a>
                <?php } ?>

            </div>
            <div class="double">
                <?php if (isset($images_inspirations[3])) { ?>
                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[3]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[3]?>" alt="">
                </a>
                <?php } ?>
                <?php if (isset($images_inspirations[4])) { ?>
                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[4]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[4]?>" alt="">
                </a>
                <?php } ?>

            </div>
            <div class="single">
            <?php if (isset($images_inspirations[5])) { ?>
                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[5]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[5]?>" alt="">
                </a>
                <?php } ?>

            </div>
            <div class="single">
                <?php if (isset($images_inspirations[6])) { ?>

                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[6]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[6]?>" alt="">
                </a>
                <?php } ?>

            </div>
            <div class="double">
                <?php if (isset($images_inspirations[7])) { ?>

                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[7]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[7]?>" alt="">
                </a>
                <?php } ?>

                <?php if (isset($images_inspirations[8])) { ?>

                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[8]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[8]?>" alt="">
                </a>
                <?php } ?>

                
            </div>
            <div class="single">
            <?php if (isset($images_inspirations[9])) { ?>

                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[9]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[9]?>" alt="">
                </a>
                <?php } ?>

            </div>
            <div class="double">
            <?php if (isset($images_inspirations[10])) { ?>

                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[10]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[10]?>" alt="">
                </a>
                <?php } ?>

                <?php if (isset($images_inspirations[11])) { ?>

                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[11]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[11]?>" alt="">
                </a>
                <?php } ?>

            </div>
            <div class="double">
            <?php if (isset($images_inspirations[12])) { ?>

                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[12]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[12]?>" alt="">
                </a>
                <?php } ?>

                <?php if (isset($images_inspirations[13])) { ?>

                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[13]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[13]?>" alt="">
                </a>
                <?php } ?>

            </div>
            <div class="single">
            <?php if (isset($images_inspirations[14])) { ?>

                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[14]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[14]?>" alt="">
                </a>
                <?php } ?>

            </div>
            <div class="double">
            <?php if (isset($images_inspirations[15])) { ?>

                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[15]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[15]?>" alt="">
                </a>
                <?php } ?>

                <?php if (isset($images_inspirations[16])) { ?>

                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[16]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[16]?>" alt="">
                </a>
                <?php } ?>

            </div>
            <div class="single">
            <?php if (isset($images_inspirations[17])) { ?>
                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[17]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[17]?>" alt="">
                </a>
                <?php } ?>

            </div>

            <div class="single">
            <?php if (isset($images_inspirations[18])) { ?>

                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[18]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[18]?>" alt="">
                </a>
                <?php } ?>

            </div>
            <div class="double">
            <?php if (isset($images_inspirations[19])) { ?>

                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[19]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[19]?>" alt="">
                </a>
                <?php } ?>

                <?php if (isset($images_inspirations[20])) { ?>

                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[20]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[20]?>" alt="">
                </a>
                <?php } ?>

            </div>
            <div class="single">
            <?php if (isset($images_inspirations[21])) { ?>

                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[21]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[21]?>" alt="">
                </a>
                <?php } ?>

            </div>
            <div class="double">
            <?php if (isset($images_inspirations[22])) { ?>

                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[22]?>">
                    <img src="img/imagesInspirations/<?= $images_inspirations[22]?>" alt="">
                </a>
                <?php } ?>

                <?php if (isset($images_inspirations[23])) { ?>

                <a class="lightbox" href="img/imagesInspirations/<?= $images_inspirations[23]?>g">
                    <img src="img/imagesInspirations/<?= $images_inspirations[23]?>" alt="">
                </a>
                <?php } ?>

            </div>

        </div>

    </div>

</div>




<div class="partenaires">

    <h1 class="align-center"><?= $titre_inspirations ?></h1>

    <div class="texte-liens align-center">
        <?= $texte_inspirations ?>
    </div>

</div>




<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
<script>
    baguetteBox.run('.tz-gallery');
</script>
