
<main>
    <div class="missions-header">
        <div class="image-slogan align-center">
            <img src="<?=$image_mission_header?>" alt="">
            <p class="slogan">
            <?= $text_image_mission_header ?>
            </p>
        </div>
    </div>
    <div class="intro-missions">
        <?= $text_mission_intro ?>
    </div>
    <div class="missions">
        <div></div>
    </div>
</main>
