
<main>
    <section class="missions-header">
        <div class="image-slogan align-center overflow-hidden width-100 height-500 spinner">
            <img class="width-100 loading-image" src="<?=$image_mission_header?>" alt="">
        </div>
        <div class="slogan block width-max-content max-width-80 align-center margin-auto padding-1 background-grey">
            <?= $text_image_mission_header ?>
        </div>
    </section>
    <div class="intro-missions max-width-60 margin-auto font-2-5 text-align-center">
        <?= $text_mission_intro ?>
    </div>
    <div class="missions max-width-1200 margin-auto">
    <?php foreach ($missions as $key => $mission) { ?>
    <div class="display-flex flex-row">
        <div class="width-50pc overflow-hidden height-400 spinner">
            <img class="loading-image" src="<?=$to_root?>img/imagesBlocsMissions/<?=$mission['image']?>" alt="">
        </div>    
        <div class="ml-3 max-width-550">
            <div class="font-3">    
                <?= $mission['titre'] ?>
            </div>
            <div class="font-2-5 pt-1">
                <?= $mission['texte'] ?>
            </div>
        </div>
    </div>
        <?php } ?>
    </div>
</main>
<script src="<?=$to_root?>js/images.js"></script>

