
<main>

<section id="mosaique" class="container">

<?php foreach ($allPublishedProjects as $theProject) { ?>

	<div class="imageMosaique spinner">
		<a href="/index/projet?n=<?=$theProject['id']?> ">
			<img class="loading-image" src="<?=$to_root?>img/imagesArticles/<?=$theProject['imageTitre']?>">
			<div class="texteVignette"><?=$theProject['texteGalerie']?></div>
		</a>
	</div>

<?php } ?>

</section>

<script src="<?=$to_root?>js/images.js"></script>


</main>
