<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="css/normalize.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="css/admin.css">
	<script
			  src="https://code.jquery.com/jquery-3.4.1.min.js"
			  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
			  crossorigin="anonymous"></script>
	<link href='https://cdn.jsdelivr.net/npm/froala-editor@3.0.0-rc.2/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
	<script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@3.0.0-rc.2/js/froala_editor.pkgd.min.js'></script>
	<script type='text/javascript' src='js/admin.js'></script>
	<title>Modifier un projet</title>

</head>

<section id="nouveauProjet">

<div class="articleTools">
	<a href="admin.php">Retour à l'accueil</a>
</div>

		<h2>- Modifier un projet -</h2>

		<form action="?pid=<?=$theProject['id'] ?>" method="POST">

			<label for="title">Titre du projet :</label>
			<input type="text" placeholder="" value="<?=$theProject['titre'] ?>" id="title" name="title">

			<label for="galleryText">Texte de présentation (galerie) :</label>
			<textarea name="galleryText" id="galleryText" cols="30" rows="5"><?=$theProject['texteGalerie'] ?></textarea>

			<label for="subtitle">Sous-titre :</label>
			<textarea name="subtitle" id="subtitle" cols="30" rows="5"><?=$theProject['sousTitre'] ?></textarea>

			<label for="text">Texte :</label>
			<textarea name="text" id="text" cols="30" rows="10"><?=$theProject['texte'] ?></textarea>
			
			<input id="submitNewProject" type="submit" value="Enregistrer">

		</form>
