<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="css/normalize.css">
	<link rel="stylesheet" type="text/css" href="css/admin.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<title>Modifier un projet</title>
</head>

<section id="nouveauProjet">

		<h2>- Modifier un projet -</h2>

		<form action="?pid=<?=$theProject['id'] ?>" method="POST">

			<label for="title">Titre du projet :</label>
			<input type="text" placeholder="" value="<?=$theProject['titre'] ?>" id="title" name="title">

			<label for="galleryText">Texte de présentation (galerie) :</label>
			<textarea name="galleryText" id="galleryText" cols="30" rows="5"><?=$theProject['texteGalerie'] ?></textarea>

			<label for="subtitle">Sous-titre :</label>
			<textarea name="subtitle" id="subtitle" cols="30" rows="5"><?=$theProject['sousTitre'] ?></textarea>

			<label for="text">Texte :</label>
			<textarea name="text" id="text" cols="30" rows="10"><?=$theProject['texte'] ?></textarea>

			<input class="hidden" type="text" value="<?=$theProject['id'] ?>" id="pid" name="pid">
			
			<input id="submitNewProject" type="submit" value="Enregistrer et passer aux images">

		</form>

	</section>

