
<main>
	
	<article class="articleProjet container">
		
		<div class="blocImages">

			<?php foreach ($theProject['imagesArticle'] as $image) { 

				if ($image != "" && $image != " "){

				?>

				<img src="img/imagesArticles/<?= $image ?>" alt="Projet Émilie Robert">
		
			<?php } 
		
			} ?>
			
		</div>

		<aside class="asideProjet">

			<h1 class="titreArticle"><?= $theProject['titre'] ?></h1>
			<div class="sousTitreArticle"><?= $theProject['sousTitre'] ?></div>
			<div class="texteArticle"><?= $theProject['texte'] ?></div>
			<div class="imagesCorpsArticle">
			
			<?php foreach ($theProject['imagesTextArticle'] as $image) {
				
				if ($image != "" && $image != " "){

					?>
	
					<img src="img/imagesArticles/<?= $image ?>" alt="Projet Émilie Robert">
			
				<?php } 
	

			} ?>

			</div>

		</aside>

		<div class="clear"></div>

	</article>

</main>