
<main>
	
	<article class="articleProjet container">
		
		<div class="blocImages">

			<?php foreach ($theProject['imagesArticle'] as $image) { ?>

				<img src="img/imagesArticles/<?= $image ?>" alt="Projet Émilie Robert">
		
			<?php } ?>
			
		</div>

		<aside class="asideProjet">

			<h1 class="titreArticle"><?= $theProject['titre'] ?></h1>
			<div class="sousTitreArticle"><?= $theProject['sousTitre'] ?></div>
			<div class="texteArticle"><?= $theProject['texte'] ?></div>

		</aside>

		<div class="clear"></div>

	</article>

</main>